
# These variables are build-specific and should be passed via the --set parameter.
nginx:
  image: 'you need to pass in a value for nginx.image to your helm chart'
drupal:
  image: 'you need to pass in a value for drupal.image to your helm chart'
  # will be generated random hashsalt if not provided here
  # need to be base64 encoded
  hashsalt: "template-hash-salt" 
  env:
  #these are added to drupal environment
    PHP_FPM_CLEAR_ENV: "no"

  # Create a volume for private files.
  privateFiles:
    enabled: false

  postinstall:
    command: |
      cd web;
      conf_count=$(ls ../config/sync/ | wc -l);
      if [ $conf_count -gt 1 ]; then drush site-install -n config_installer;
      else drush site-install minimal -y;
      fi;

  postupgrade:
    command: |
      cd web;
      conf_count=$(ls ../config/sync/ | wc -l);
      if [ $conf_count -gt 1 ]; then drush updatedb -n; drush config-import -n; drush entity-updates -n;
      fi;

mariadb:
  replication:
    enabled: false
  db:
    name: drupal
    user: drupal

clusterDomain: "silta.wdr.io"
branchname: "default"
