
# These variables are build-specific and should be passed via the --set parameter.
nginx:
  image: 'you need to pass in a value for nginx.image to your helm chart'
drupal:
  image: 'you need to pass in a value for drupal.image to your helm chart'

  cron:
    - schedule: '0 * * * *'
      command: 'drush cron'
    - schedule: '*/5 * * * *'
      command: 'bootstrapped=$(drush status --field=bootstrap);
        if [[ $bootstrapped = "Successful" ]] && [[ "$BRANCHNAME" = "$PRODUCTION_BRANCHNAME" ]];
        then
          export PATH=../vendor/bin:$PATH;
          drush sql-dump --extra-dump="--gdpr-replacements-file=../gdpr.json" --result-file /var/backups/db/${BRANCHNAME//[^[:alnum:]]/-}-latest.sql;
        fi;'

  # will be generated random hashsalt if not provided here
  # need to be base64 encoded
  hashsalt: "template-hash-salt" 
  env:
  #these are added to drupal environment
    PHP_FPM_CLEAR_ENV: "no"

  # Create a volume for private files.
  privateFiles:
    enabled: false

  postinstall:
    command: |
      cd web;
      conf_count=$(ls ../config/sync/ | wc -l);
      if [ $conf_count -gt 1 ]; then drush site-install -n config_installer;
      else drush site-install minimal -y;
      fi;

  postupgrade:
    command: |
      cd web;
      conf_count=$(ls ../config/sync/ | wc -l);
      if [ $conf_count -gt 1 ]; then drush updatedb -n; drush config-import -n; drush entity-updates -n;
      fi;

mariadb:
  replication:
    enabled: false
  rootUser:
    password: "{{ randAlphaNum 10 }}" # pass in a value to your helm chart to override this
  db:
    name: drupal
    user: drupal
    password: "{{ randAlphaNum 10 }}" # pass in a value to your helm chart to override this

# Cluster configuration.
clusterDomain: "silta.wdr.io"

# Configure image pull secrets for the containers. This is not needed on GKE.
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

branchname: "default"
production_branchname: "feature/SLT-17-gdpr-dump"
