#/var/www/html/vendor/drush/drush
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  backOffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            image: "{{ .Values.drupal.image }}"
            command:
            - echo
            - "THIS IS A TEST MESSAGE"
            env:
            - name: PHP_FPM_CLEAR_ENV
              value: "no"
            - name: DB_USER
              value: "{{ .Values.mariadb.db.user }}"
            - name: DB_NAME
              value: "{{ .Values.mariadb.db.name }}"
            - name: DB_HOST
              value: "{{ .Release.Name }}-mariadb"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-mariadb"
                  key: mariadb-password
          restartPolicy: OnFailure
