apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
  annotations:
{{- if .Values.ambassador.enabled }}
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-drupal
      host: {{ template "drupal.domain" . }}
      service: {{ .Release.Name }}-drupal.{{ .Release.Namespace }}.svc.cluster.local:80
      {{- .Values.ambassador.config | toYaml | nindent 6 }}
{{- end }}
    domain: {{ template "drupal.domain" . }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
  selector:
    {{- include "drupal.release_labels" . | nindent 4 }}
    deployment: drupal