apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-{{ .Release.Namespace }}-0
  namespace: {{ .Release.Namespace }}
  labels:
    for_app: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-nfs-{{ .Release.Namespace }}-0
    namespace: {{ .Release.Namespace }}
  gcePersistentDisk:
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-backups-claim
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      for_app: {{ .Release.Namespace }}
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
